
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shinano_quanti?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: helei
    password: 962464helei
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 输出 SQL 日志

  kafka:

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  data:
    redis:
      # 如果需要密码，格式为 redis://:password@localhost:6379
      url: redis://192.168.1.2:6379
