shinano:
  quantity:
    trade_app:
      run_type:
        configs:
          - env: NORMAL
            trade_type:
              - SPOT

      kafka:
        #        bootstrap_servers: 127.0.0.1:9092 # Kafka服务器地址
        bootstrap_servers: 192.168.1.3:9092 # Kafka服务器地址
        group_id: trade_app_test_group
        kafka_num_partitions: 1
        kafka_replication_factor: 1

      redis:
        # 如果需要密码，格式为 redis://:password@localhost:6379
        #        url: redis://127.0.0.1:6379
        url: redis://192.168.1.3:6379

      # 信号设置
      signal:
        # 运行环境
        normal:
          # 交易类型
          spot:
            - symbol: btcusdt # 交易对名称
              signal_names: # 信号名list
                - test1
                - test2
                - test3
            - symbol: ethusdt
              signal_names:
                - test1
                - test2
                - test3
          contract:
            - symbol: btcusdt
              signal_names:
                - test1
                - test2
                - test3
            - symbol: ethusdt
              signal_names:
                - test1
                - test2
                - test3
        test_net: {}
