pipeline.serialization-config:
  - com.helei.dto.trade.KLine :  {type: kryo, kryo-type: registered, class: com.helei.tradesignalprocess.serialization.KLineSerializer}
  - com.helei.dto.trade.IndicatorMap: {type: kryo, kryo-type: registered, class: com.helei.tradesignalprocess.serialization.IndicatorMapSerializer}
  - com.helei.constants.trade.KLineInterval: {type: kryo, kryo-type: registered, class: com.helei.tradesignalprocess.serialization.KLineIntervalSerializer}
