pipeline.serialization-config:
  - com.helei.dto.KLine :  {type: kryo, kryo-type: registered, class: com.helei.tradesignalcenter.serialization.KLineSerializer}
  - com.helei.dto.IndicatorMap: {type: kryo, kryo-type: registered, class: com.helei.tradesignalcenter.serialization.IndicatorMapSerializer}
  - com.helei.constants.KLineInterval: {type: kryo, kryo-type: registered, class: com.helei.tradesignalcenter.serialization.KLineIntervalSerializer}
