shinano:
  quantity:
    # 信号生成服务配置
    trade_signal_maker:
      # name
      name: test
      # symbol
      symbol: btcusdt
      # 运行环境
      run_env: NORMAL
      # 交易类型
      trade_type: CONTRACT
      # 历史k线加载批大小
      historyKLineBatchSize: 200
      # 批加载的网络并发度
      batchLoadConcurrent: 10
      # 实时数据配置
      realtime:
        # kafka配置
        kafka:
          input:
            bootstrapServer: 192.168.1.2:9092
            groupId: trade_signal_app_test
            transaction_timeout_ms: 900000

          output:
            bootstrapServer: 192.168.1.2:9092
            groupId: trade_signal_app_test
            transaction_timeout_ms: 900000

        # flink配置
        flink:
          jobManagerHost: 192.168.1.2
          jobManagerPort: 8081
