shinano:
  quantity:
    realtime:
      run_type:
        configs:
          #          - env: NORMAL
          #            trade_type:
          #              - SPOT
          #              - CONTRACT
          - env: TEST_NET
            trade_type:
              - SPOT
      #              - CONTRACT

      kafka:
        bootstrap_servers: 192.168.1.3:9092 # Kafka服务器地址
        kafka_num_partitions: 1
        kafka_replication_factor: 1
      redis:
        # 如果需要密码，格式为 redis://:password@localhost:6379
        url: redis://192.168.1.3:6379

      # 测试网配置
      test_net:
        #现货配置
        spot:
          # 监听的k线
          listen_kline:
            - BTCUSDT@24h
            - ETHUSDT@1m
          # 一个ws客户端监听k线的最大数量
          client_listen_kline_max_count: 15
        # 合约配置
        contract:
          listen_kline:
            - BTCUSDT@15m,1h
            - ETHUSDT@15m,1h
          client_listen_kline_max_count: 15
      # 主网配置
      normal:
        #现货配置
        spot:
          # 监听的k线
          listen_kline:
            - SOLUSDT@15m,1h
            - BTCUSDT@15m,1h
          # 一个ws客户端监听k线的最大数量
          client_listen_kline_max_count: 15
        # 合约配置
        contract:
          listen_kline:
            - BTCUSDT@1m,15m,1h,1d
            - ETHUSDT@1m,15m,1h,1d
          client_listen_kline_max_count: 15
