

asKey:
  test:
    spot:
      apiKey: 1JIhkPyK07xadG9x8hIwqitN95MgpypPzA4b6TLraTonRnJ8BBJQlaO2iL9tPH0Y
      secretKey: t84TYFR1zieMGncbw3kYq4zAPLxIJHJeMdD8V0FMKxij9fApojV6bhbDpyyjNDWt
    contract:
      apiKey: b252246c6c6e81b64b8ff52caf6b8f37471187b1b9086399e27f6911242cbc66
      secretKey: a4ed1b1addad2a49d13e08644f0cc8fc02a5c14c3511d374eac4e37763cadf5f

spring:
  application:
    name: TradeSignalCenter
