

shinano:
  quantity:
    realtime:
      kafka:
        bootstrapServer: 192.168.1.2:9092
        groupId: trade_signal_app_test
      flink:
        jobManagerHost: 192.168.1.2
        jobManagerPort: 8081
